version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/auth?authSource=admin
      - NODE_ENV=dev
    env_file:
      - ./config/.env.dev
    depends_on:
      - mongo

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    container_name: event
    ports:
      - '3002:3000'
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/auth?authSource=admin
      - NODE_ENV=dev
    env_file:
      - ./config/.env.dev
    depends_on:
      - mongo

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=dev
    env_file:
      - ./config/.env.dev
    depends_on:
      - auth
      - event
volumes:
  mongo-data:
